specVersion: 1.0.0
name: astar-evm-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: ALgem nASTR Indexer 1
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  endpoint: 'wss://astar.api.onfinality.io/ws?apikey=fb87f723-10f2-4952-89b0-1c50224faad6'
#  endpoint: 'wss://astar.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/astar-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/FrontierEvm
#    startBlock: 2012494
    startBlock: 1506340
    processor:
      file: ./node_modules/@subql/frontier-evm-processor/dist/bundle.js
#      options:
#        abi: erc20
#    assets:
#      erc20:
#        file: ./erc20.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvmEventStaked
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - 'Staked(address indexed user,uint256 val)'
#        - handler: handleEvmCallStake
#          kind: substrate/FrontierEvmCall
#          filter:
#            function: '0x3a4b66f1'
#        - handler: handleEvmCallUnstake
#          kind: substrate/FrontierEvmCall
#          filter:
#            function: '0x9ebea88c'
#        - handler: handleEvmCallClaim
#          kind: substrate/FrontierEvmCall
#          filter:
#            function: '0x379607f5'
#        - handler: handleEvmCallAddLiquidity
#          kind: substrate/FrontierEvmCall
#          filter:
#            function: '0xeeda2504'
#        - handler: handleEvmCallDepositLP
#          kind: substrate/FrontierEvmCall
#          filter:
#            function: '0xeb37acfc'
